export const EMOJIS = {
  "Visages & émotions": [
    { symbol: "😀", name: "visage souriant" },
    { symbol: "😁", name: "visage rayonnant" },
    { symbol: "😂", name: "visage pleurant de rire" },
    { symbol: "🤣", name: "roulant par terre de rire" },
    { symbol: "😃", name: "visage souriant avec de grands yeux" },
    { symbol: "😄", name: "visage souriant avec des yeux rieurs" },
    { symbol: "😅", name: "visage souriant avec sueur froide" },
    { symbol: "😆", name: "visage rieur" },
    { symbol: "😉", name: "clin d'œil" },
    { symbol: "😊", name: "visage souriant avec des yeux souriants" },
    { symbol: "😋", name: "visage savourant" },
    { symbol: "😎", name: "visage avec des lunettes de soleil" },
    { symbol: "😍", name: "visage avec des cœurs dans les yeux" },
    { symbol: "😘", name: "visage envoyant un baiser" },
    { symbol: "😗", name: "visage faisant un bisou" },
    { symbol: "😙", name: "visage faisant un bisou avec des yeux souriants" },
    { symbol: "😚", name: "visage faisant un bisou avec des yeux fermés" },
    { symbol: "🙂", name: "visage légèrement souriant" },
    { symbol: "🤗", name: "visage étreignant" },
    { symbol: "🤩", name: "visage avec des étoiles dans les yeux" },
    { symbol: "🤔", name: "visage pensif" },
    { symbol: "🤨", name: "visage avec un sourcil levé" },
    { symbol: "😐", name: "visage neutre" },
    { symbol: "😑", name: "visage sans expression" },
    { symbol: "😶", name: "visage sans bouche" },
    { symbol: "🙄", name: "visage avec les yeux levés" },
    { symbol: "😏", name: "visage narquois" },
    { symbol: "😣", name: "visage persévérant" },
    { symbol: "😥", name: "visage déçu mais soulagé" },
    { symbol: "😮", name: "visage étonné" },
    { symbol: "🤐", name: "visage avec la bouche fermée" },
    { symbol: "😯", name: "visage surpris" },
    { symbol: "😪", name: "visage somnolent" },
    { symbol: "😫", name: "visage épuisé" },
    { symbol: "😴", name: "visage endormi" },
    { symbol: "😌", name: "visage soulagé" },
    { symbol: "😛", name: "visage tirant la langue" },
    { symbol: "😜", name: "visage tirant la langue et clin d'œil" },
    { symbol: "😝", name: "visage tirant la langue avec les yeux fermés" },
    { symbol: "🤤", name: "visage bavant" },
    { symbol: "😒", name: "visage mécontent" },
    { symbol: "😓", name: "visage avec sueur froide" },
    { symbol: "😔", name: "visage pensif" },
    { symbol: "😕", name: "visage confus" },
    { symbol: "🙃", name: "visage à l'envers" },
    { symbol: "🤑", name: "visage avec des signes de dollar" },
    { symbol: "😲", name: "visage choqué" },
    { symbol: "☹️", name: "visage légèrement triste" },
    { symbol: "🙁", name: "visage légèrement triste" },
    { symbol: "😖", name: "visage confus" },
    { symbol: "😞", name: "visage déçu" },
    { symbol: "😟", name: "visage inquiet" },
    { symbol: "😤", name: "visage avec de la vapeur du nez" },
    { symbol: "😢", name: "visage pleurant" },
    { symbol: "😭", name: "visage en larmes" },
    { symbol: "😦", name: "visage bouche ouverte" },
    { symbol: "😧", name: "visage angoissé" },
    { symbol: "😨", name: "visage effrayé" },
    { symbol: "😩", name: "visage fatigué" },
    { symbol: "🤯", name: "tête qui explose" },
    { symbol: "😬", name: "visage grimaçant" },
    { symbol: "😰", name: "visage anxieux avec sueur" },
    { symbol: "😱", name: "visage criant de peur" },
    { symbol: "🥵", name: "visage chaud" },
    { symbol: "🥶", name: "visage froid" },
    { symbol: "😳", name: "visage rougissant" },
    { symbol: "🤪", name: "visage fou" },
    { symbol: "😵", name: "visage abasourdi" },
    { symbol: "😠", name: "visage fâché" },
    { symbol: "😡", name: "visage en colère" },
    { symbol: "🤬", name: "visage avec des symboles sur la bouche" },
    { symbol: "😷", name: "visage avec un masque médical" },
    { symbol: "🤒", name: "visage malade" },
    { symbol: "🤕", name: "visage blessé" },
    { symbol: "🤢", name: "visage nauséeux" },
    { symbol: "🤮", name: "visage vomissant" },
    { symbol: "🤧", name: "visage éternuant" },
    { symbol: "💩", name: "caca" },
    { symbol: "💀", name: "crâne" },
    { symbol: "👻", name: "fantôme" },
    { symbol: "👽", name: "visage avec masque de gaz" },
    { symbol: "🤖", name: "robot" },
    { symbol: "🎃", name: "citrouille d'Halloween" },
    { symbol: "😈", name: "visage souriant avec des cornes" },
  ],
  "Gestes & mains": [
    { symbol: "💪", name: "biceps fléchi" },
    { symbol: "🖐️", name: "main ouverte" },
    { symbol: "✋", name: "main levée" },
    { symbol: "🤚", name: "main levée vers l’arrière" },
    { symbol: "🖖", name: "salut vulcain" },
    { symbol: "👌", name: "signe OK" },
    { symbol: "🤌", name: "main pincée" },
    { symbol: "🤏", name: "main serrant un petit objet" },
    { symbol: "✌️", name: "signe de la paix" },
    { symbol: "🤞", name: "doigts croisés" },
    { symbol: "🫰", name: "geste de l’argent (doigts pincés)" },
    { symbol: "🤟", name: "je t’aime en langue des signes" },
    { symbol: "🤘", name: "signe des cornes" },
    { symbol: "🤙", name: "geste accroche-moi" },
    { symbol: "👈", name: "main pointant à gauche" },
    { symbol: "👉", name: "main pointant à droite" },
    { symbol: "👆", name: "main pointant vers le haut" },
    { symbol: "👇", name: "main pointant vers le bas" },
    { symbol: "☝️", name: "main levée avec index" },
    { symbol: "👍", name: "pouce levé" },
    { symbol: "👎", name: "pouce baissé" },
    { symbol: "✊", name: "poing levé" },
    { symbol: "👊", name: "coup de poing" },
    { symbol: "🤛", name: "poing vers la gauche" },
    { symbol: "🤜", name: "poing vers la droite" },
    { symbol: "👏", name: "mains applaudissant" },
    { symbol: "👐", name: "mains ouvertes" },
    { symbol: "🤲", name: "mains en prière" },
    { symbol: "🙏", name: "mains jointes" },
    { symbol: "✍️", name: "main écrivant" },
    { symbol: "💅", name: "pose de vernis à ongles" },
  ],
  "Personnes & corps": [
    { symbol: "👶", name: "bébé" },
    { symbol: "👧", name: "fille" },
    { symbol: "🧒", name: "enfant" },
    { symbol: "👦", name: "garçon" },
    { symbol: "👩", name: "femme" },
    { symbol: "🧑", name: "personne" },
    { symbol: "👨", name: "homme" },
    { symbol: "🧔", name: "homme barbu" },
    { symbol: "👵", name: "vieille femme" },
    { symbol: "🧓", name: "personne âgée" },
    { symbol: "👴", name: "vieux homme" },
    { symbol: "🙍‍♀️", name: "femme faisant la moue" },
    { symbol: "🙍‍♂️", name: "homme faisant la moue" },
    { symbol: "🙎‍♀️", name: "femme se plaignant" },
    { symbol: "🙎‍♂️", name: "homme se plaignant" },
    { symbol: "🙅‍♀️", name: "femme faisant un signe de non" },
    { symbol: "🙅‍♂️", name: "homme faisant un signe de non" },
    { symbol: "🙆‍♀️", name: "femme faisant un signe de oui" },
    { symbol: "🙆‍♂️", name: "homme faisant un signe de oui" },
    { symbol: "💁‍♀️", name: "femme avec une main levée" },
    { symbol: "💁‍♂️", name: "homme avec une main levée" },
  ],
  Activités: [
    { symbol: "⚽", name: "football" },
    { symbol: "🏀", name: "basket-ball" },
    { symbol: "🏈", name: "football américain" },
    { symbol: "⚾", name: "baseball" },
    { symbol: "🎾", name: "tennis" },
    { symbol: "🏐", name: "volley-ball" },
    { symbol: "🏉", name: "rugby" },
    { symbol: "🎱", name: "billard" },
    { symbol: "🎳", name: "bowling" },
  ],
  Lieux: [
    { symbol: "🏠", name: "maison" },
    { symbol: "🏡", name: "maison avec jardin" },
    { symbol: "🏢", name: "immeuble de bureaux" },
    { symbol: "🏣", name: "bureau de poste" },
    { symbol: "🏤", name: "banque" },
    { symbol: "🏥", name: "hôpital" },
    { symbol: "🏦", name: "banque" },
    { symbol: "🏨", name: "hôtel" },
  ],
  Objets: [
    { symbol: "📱", name: "téléphone portable" },
    { symbol: "💻", name: "ordinateur portable" },
    { symbol: "🖥️", name: "ordinateur de bureau" },
    { symbol: "🖨️", name: "imprimante" },
    { symbol: "🖱️", name: "souris d'ordinateur" },
    { symbol: "⌨️", name: "clavier" },
    { symbol: "💡", name: "ampoule" },
  ],
  Symboles: [
    { symbol: "❤️", name: "cœur rouge" },
    { symbol: "💔", name: "cœur brisé" },
    { symbol: "💖", name: "cœur brillant" },
    { symbol: "💗", name: "cœur en mouvement" },
    { symbol: "💓", name: "cœur battant" },
    { symbol: "💞", name: "deux cœurs entrelacés" },
    { symbol: "💕", name: "deux cœurs" },
  ],
  Transports: [
    { symbol: "🚗", name: "voiture" },
    { symbol: "🚕", name: "taxi" },
    { symbol: "🚙", name: "SUV" },
    { symbol: "🚌", name: "autobus" },
    { symbol: "🚎", name: "trolleybus" },
    { symbol: "🏍️", name: "moto" },
    { symbol: "🚲", name: "vélo" },
  ],
  "Nourriture & Boissons": [
    { symbol: "🍏", name: "pomme verte" },
    { symbol: "🍎", name: "pomme rouge" },
    { symbol: "🍐", name: "poire" },
    { symbol: "🍊", name: "orange" },
    { symbol: "🍋", name: "citron" },
    { symbol: "🍌", name: "banane" },
    { symbol: "🍉", name: "pastèque" },
    { symbol: "☕", name: "café" },
    { symbol: "🍵", name: "thé" },
    { symbol: "🍶", name: "sake" },
    { symbol: "🍺", name: "bière" },
    { symbol: "🍻", name: "bières" },
    { symbol: "🥂", name: "flûte de champagne" },
    { symbol: "🍷", name: "verre de vin" },
  ],
  "Animaux & Nature": [
    { symbol: "🐶", name: "chien" },
    { symbol: "🐱", name: "chat" },
    { symbol: "🐭", name: "souris" },
    { symbol: "🐹", name: "hamster" },
    { symbol: "🐰", name: "lapin" },
    { symbol: "🦊", name: "renard" },
    { symbol: "🐻", name: "ours" },
    { symbol: "🐧", name: "pingouin" },
    { symbol: "🐦", name: "oiseau" },
    { symbol: "🦅", name: "aigle" },
    { symbol: "🦉", name: "hibou" },
    { symbol: "🦩", name: "flamant rose" },
    { symbol: "🐠", name: "poisson" },
    { symbol: "🐟", name: "poisson" },
    { symbol: "🐡", name: "poisson-globe" },
    { symbol: "🐬", name: "dauphin" },
    { symbol: "🐳", name: "baleine" },
    { symbol: "🐋", name: "baleine" },
    { symbol: "🐍", name: "serpent" },
    { symbol: "🦎", name: "lézard" },
    { symbol: "🐊", name: "crocodile" },
    { symbol: "🐢", name: "tortue" },
    { symbol: "🐜", name: "fourmi" },
    { symbol: "🐝", name: "abeille" },
    { symbol: "🦋", name: "papillon" },
    { symbol: "🐞", name: "coccinelle" },
    { symbol: "🦗", name: "sauterelle" },
    { symbol: "🕷️", name: "araignée" },
    { symbol: "🕸️", name: "toile d'araignée" },
    { symbol: "🌳", name: "arbre" },
    { symbol: "🌲", name: "sapin" },
    { symbol: "🌴", name: "palmier" },
    { symbol: "🌵", name: "cactus" },
    { symbol: "🌾", name: "herbe" },
    { symbol: "🍀", name: "trèfle" },
    { symbol: "🌹", name: "rose" },
    { symbol: "🌻", name: "tournesol" },
    { symbol: "🌼", name: "fleur" },
    { symbol: "🌸", name: "fleur de cerisier" },
    { symbol: "🌺", name: "hibiscus" },
    { symbol: "🌷", name: "tulipe" },
    { symbol: "🌿", name: "feuille" },
  ],
};
