export const EMOJIS = {
  "Visages & émotions": [
    { symbol: "😀", name: "Souriant" },
    { symbol: "😁", name: "Rayonnant" },
    { symbol: "😂", name: "Pleurant de rire" },
    { symbol: "🤣", name: "Roulant par terre de rire" },
    { symbol: "😃", name: "Souriant avec de grands yeux" },
    { symbol: "😄", name: "Souriant avec des yeux rieurs" },
    { symbol: "😅", name: "Souriant avec sueur froide" },
    { symbol: "😆", name: "Rieur" },
    { symbol: "😉", name: "Clin d'œil" },
    { symbol: "😊", name: "Souriant avec des yeux souriants" },
    { symbol: "😋", name: "Savourant" },
    { symbol: "😎", name: "Avec des lunettes de soleil" },
    { symbol: "😍", name: "Avec des cœurs dans les yeux" },
    { symbol: "😘", name: "Envoyant un baiser" },
    { symbol: "😗", name: "Faisant un bisou" },
    { symbol: "😙", name: "Faisant un bisou avec des yeux souriants" },
    { symbol: "😚", name: "Faisant un bisou avec des yeux fermés" },
    { symbol: "🙂", name: "Légèrement souriant" },
    { symbol: "🤗", name: "Étreignant" },
    { symbol: "🤩", name: "Avec des étoiles dans les yeux" },
    { symbol: "🤔", name: "Pensif" },
    { symbol: "🤨", name: "Avec un sourcil levé" },
    { symbol: "😐", name: "Neutre" },
    { symbol: "😑", name: "Sans expression" },
    { symbol: "😶", name: "Sans bouche" },
    { symbol: "🙄", name: "Avec les yeux levés" },
    { symbol: "😏", name: "Narquois" },
    { symbol: "😣", name: "Persévérant" },
    { symbol: "😥", name: "Déçu mais soulagé" },
    { symbol: "😮", name: "Étonné" },
    { symbol: "🤐", name: "Avec la bouche fermée" },
    { symbol: "😯", name: "Surpris" },
    { symbol: "😪", name: "Somnolent" },
    { symbol: "😫", name: "Épuisé" },
    { symbol: "😴", name: "Endormi" },
    { symbol: "😌", name: "Soulagé" },
    { symbol: "😛", name: "Tirant la langue" },
    { symbol: "😜", name: "Tirant la langue et clin d'œil" },
    { symbol: "😝", name: "Tirant la langue avec les yeux fermés" },
    { symbol: "🤤", name: "Bavant" },
    { symbol: "😒", name: "Mécontent" },
    { symbol: "😓", name: "Sueur froide" },
    { symbol: "😔", name: "Pensif" },
    { symbol: "😕", name: "Confus" },
    { symbol: "🙃", name: "A l'envers" },
    { symbol: "🤑", name: "Avec des signes de dollar" },
    { symbol: "😲", name: "Choqué" },
    { symbol: "☹️", name: "Triste" },
    { symbol: "😖", name: "Confus" },
    { symbol: "😞", name: "Déçu" },
    { symbol: "😟", name: "Inquiet" },
    { symbol: "😤", name: "Avec de la vapeur du nez" },
    { symbol: "😢", name: "Pleurant" },
    { symbol: "😭", name: "En larmes" },
    { symbol: "😦", name: "Bouche ouverte" },
    { symbol: "😧", name: "Angoissé" },
    { symbol: "😨", name: "Effrayé" },
    { symbol: "😩", name: "Fatigué" },
    { symbol: "🤯", name: "Tête qui explose" },
    { symbol: "😬", name: "Grimaçant" },
    { symbol: "😰", name: "Anxieux avec sueur" },
    { symbol: "😱", name: "Criant de peur" },
    { symbol: "🥵", name: "Chaud" },
    { symbol: "🥶", name: "Froid" },
    { symbol: "😳", name: "Rougissant" },
    { symbol: "🤪", name: "Fou" },
    { symbol: "😵", name: "Abasourdi" },
    { symbol: "😠", name: "Fâché" },
    { symbol: "😡", name: "En colère" },
    { symbol: "🤬", name: "Avec des symboles sur la bouche" },
    { symbol: "😷", name: "Avec un masque médical" },
    { symbol: "🤒", name: "Malade" },
    { symbol: "🤕", name: "Blessé" },
    { symbol: "🤢", name: "Nauséeux" },
    { symbol: "🤮", name: "Vomissant" },
    { symbol: "🤧", name: "Éternuant" },
    { symbol: "💩", name: "Caca" },
    { symbol: "💀", name: "Crâne" },
    { symbol: "☠️", name: "Tête de mort" },
    { symbol: "👻", name: "Fantôme" },
    { symbol: "🤡", name: "Clown" },
    { symbol: "🧟", name: "Zombie" },
    { symbol: "👽", name: "Alien" },
    { symbol: "🤖", name: "Robot" },
    { symbol: "👀", name: "Yeux" },
    { symbol: "🎃", name: "Citrouille d'Halloween" },
    { symbol: "😈", name: "Visage souriant avec des cornes" },
  ],
  "Gestes & mains": [
    { symbol: "💪", name: "Biceps fléchi" },
    { symbol: "🖐️", name: "Main ouverte" },
    { symbol: "✋", name: "Main levée" },
    { symbol: "🤚", name: "Main levée vers l’arrière" },
    { symbol: "🖖", name: "Salut vulcain" },
    { symbol: "👌", name: "Signe OK" },
    { symbol: "🤌", name: "Main pincée" },
    { symbol: "🤏", name: "Main serrant un petit objet" },
    { symbol: "✌️", name: "Signe de la paix" },
    { symbol: "🤞", name: "Doigts croisés" },
    { symbol: "🖕", name: "Majeur" },
    { symbol: "🫰", name: "Geste de l'argent (doigts pincés)" },
    { symbol: "🤟", name: "Je t'aime en langue des signes" },
    { symbol: "🤘", name: "Signe des cornes" },
    { symbol: "🤙", name: "Geste accroche-moi" },
    { symbol: "👈", name: "Main pointant à gauche" },
    { symbol: "👉", name: "Main pointant à droite" },
    { symbol: "👆", name: "Main pointant vers le haut" },
    { symbol: "👇", name: "Main pointant vers le bas" },
    { symbol: "☝️", name: "Main levée avec index" },
    { symbol: "👍", name: "Pouce levé" },
    { symbol: "👎", name: "Pouce baissé" },
    { symbol: "✊", name: "Poing levé" },
    { symbol: "👊", name: "Coup de poing" },
    { symbol: "🤛", name: "Poing vers la gauche" },
    { symbol: "🤜", name: "Poing vers la droite" },
    { symbol: "👏", name: "Mains applaudissant" },
    { symbol: "👐", name: "Mains ouvertes" },
    { symbol: "🤲", name: "Mains en prière" },
    { symbol: "🙏", name: "Mains jointes" },
    { symbol: "✍️", name: "Main écrivant" },
    { symbol: "💅", name: "Pose de vernis à ongles" },
  ],
  "Personnes & corps": [
    { symbol: "👶", name: "Bébé" },
    { symbol: "👧", name: "Fille" },
    { symbol: "🧒", name: "Enfant" },
    { symbol: "👦", name: "Garçon" },
    { symbol: "👅", name: "Langue" },
    { symbol: "👩", name: "Femme" },
    { symbol: "🧑", name: "Personne" },
    { symbol: "👨", name: "Homme" },
    { symbol: "🧔", name: "Homme barbu" },
    { symbol: "👵", name: "Vieille femme" },
    { symbol: "🧓", name: "Personne âgée" },
    { symbol: "👴", name: "Vieil homme" },
    { symbol: "🙍‍♀️", name: "Femme faisant la moue" },
    { symbol: "🙍‍♂️", name: "Homme faisant la moue" },
    { symbol: "🙎‍♀️", name: "Femme se plaignant" },
    { symbol: "🙎‍♂️", name: "Homme se plaignant" },
    { symbol: "🙅‍♀️", name: "Femme faisant un signe de non" },
    { symbol: "🙅‍♂️", name: "Homme faisant un signe de non" },
    { symbol: "🙆‍♀️", name: "Femme faisant un signe de oui" },
    { symbol: "🙆‍♂️", name: "Homme faisant un signe de oui" },
    { symbol: "💁‍♀️", name: "Femme avec une main levée" },
    { symbol: "💁‍♂️", name: "Homme avec une main levée" },
  ],
  Activités: [
    { symbol: "⚽", name: "Football" },
    { symbol: "🏀", name: "Basket-ball" },
    { symbol: "🏈", name: "Football américain" },
    { symbol: "⚾", name: "Baseball" },
    { symbol: "🎾", name: "Tennis" },
    { symbol: "🏐", name: "Volley-ball" },
    { symbol: "🏉", name: "Rugby" },
    { symbol: "🎱", name: "Billard" },
    { symbol: "🎳", name: "Bowling" },
  ],
  Lieux: [
    { symbol: "🏠", name: "Maison" },
    { symbol: "🏡", name: "Maison avec jardin" },
    { symbol: "🏢", name: "Immeuble de bureaux" },
    { symbol: "🏣", name: "Bureau de poste" },
    { symbol: "🏤", name: "Banque" },
    { symbol: "🏥", name: "Hôpital" },
    { symbol: "🏦", name: "Banque" },
    { symbol: "🏨", name: "Hôtel" },
  ],
  Objets: [
    { symbol: "📱", name: "Téléphone portable" },
    { symbol: "💻", name: "Ordinateur portable" },
    { symbol: "🖥️", name: "Ordinateur de bureau" },
    { symbol: "🖨️", name: "Imprimante" },
    { symbol: "🖱️", name: "Souris d'ordinateur" },
    { symbol: "⌨️", name: "Clavier" },
    { symbol: "💡", name: "Ampoule" },
    { symbol: "🎁", name: "Cadeau" },
    { symbol: "🎈", name: "Ballon" },
    { symbol: "🎉", name: "Confettis" },
    { symbol: "🚬", name: "Cigarette" },
    { symbol: "🧹", name: "Balai" },
    { symbol: "💣", name: "Bombe" },
    { symbol: "🔪", name: "Couteau" },
    { symbol: "👑", name: "Couronne" },
    { symbol: "📣", name: "Porte-voix" },
    { symbol: "🎄", name: "Sapin de noël" },
  ],
  Symboles: [
    { symbol: "❤️", name: "Cœur rouge" },
    { symbol: "💔", name: "Cœur brisé" },
    { symbol: "💖", name: "Cœur brillant" },
    { symbol: "💗", name: "cœur en mouvement" },
    { symbol: "💓", name: "Cœur battant" },
    { symbol: "💞", name: "Deux cœurs entrelacés" },
    { symbol: "💕", name: "Deux cœurs" },
    { symbol: "☢️", name: "Radioactif" },
    { symbol: "💥", name: "Explosion" },
    { symbol: "💨", name: "Bourrasque" },
    { symbol: "⚠️", name: "Danger" },
  ],
  Religion: [
    { symbol: "☪️", name: "Musulman" },
    { symbol: "✝️", name: "Chrétien" },
    { symbol: "✡️", name: "Juif" },
    { symbol: "☮️", name: "Paix" },
  ],
  Transports: [
    { symbol: "🚗", name: "Voiture" },
    { symbol: "🚕", name: "Taxi" },
    { symbol: "🚙", name: "SUV" },
    { symbol: "🚌", name: "Autobus" },
    { symbol: "🚎", name: "Trolleybus" },
    { symbol: "🏍️", name: "Moto" },
    { symbol: "🚲", name: "Vélo" },
  ],
  Drapeaux: [
    { symbol: "🏳️‍🌈", name: "Arc-en-ciel" },
    { symbol: "🇫🇷", name: "France" },
    { symbol: "🇺🇸", name: "États-Unis" },
    { symbol: "🇬🇧", name: "Royaume-Uni" },
    { symbol: "🇩🇪", name: "Allemagne" },
    { symbol: "🇮🇹", name: "Italie" },
    { symbol: "🇯🇵", name: "Japon" },
    { symbol: "🇨🇦", name: "Canada" },
    { symbol: "🇦🇺", name: "Australie" },
    { symbol: "🇧🇷", name: "Brésil" },
    { symbol: "🇪🇸", name: "Espagne" },
    { symbol: "🇲🇽", name: "Mexique" },
    { symbol: "🇨🇳", name: "Chine" },
    { symbol: "🇮🇳", name: "Inde" },
    { symbol: "🇷🇺", name: "Russie" },
    { symbol: "🇿🇦", name: "Afrique du Sud" },
    { symbol: "🇰🇷", name: "Corée du Sud" },
  ],
  "Nourriture & Boissons": [
    { symbol: "🍏", name: "Pomme verte" },
    { symbol: "🍎", name: "Pomme rouge" },
    { symbol: "🍑", name: "Pêche" },
    { symbol: "🍆", name: "Aubergine" },
    { symbol: "🍫", name: "Chocolat" },
    { symbol: "🍬", name: "Bonbon" },
    { symbol: "💦", name: "Giclée" },
    { symbol: "🍐", name: "Poire" },
    { symbol: "🍊", name: "Orange" },
    { symbol: "🍋", name: "Citron" },
    { symbol: "🍌", name: "Banane" },
    { symbol: "🍉", name: "Pastèque" },
    { symbol: "☕", name: "Café" },
    { symbol: "🍵", name: "Thé" },
    { symbol: "🍶", name: "Sake" },
    { symbol: "🍺", name: "Bière" },
    { symbol: "🍻", name: "Bières" },
    { symbol: "🥂", name: "Flûte de champagne" },
    { symbol: "🍷", name: "Verre de vin" },
    { symbol: "🍭", name: "Sucette" },
    { symbol: "🍪", name: "Coockie" },
    { symbol: "🎂", name: "Gâteau d'anniversaire" },
  ],
  "Animaux & Nature": [
    { symbol: "🐶", name: "Chien" },
    { symbol: "🐵", name: "Singe" },
    { symbol: "🕊️", name: "Colombe" },
    { symbol: "🦄", name: "Licorne" },
    { symbol: "🐷", name: "Cochon" },
    { symbol: "🐱", name: "Chat" },
    { symbol: "🐭", name: "Souris" },
    { symbol: "🐹", name: "Hamster" },
    { symbol: "🐰", name: "Lapin" },
    { symbol: "🦊", name: "Renard" },
    { symbol: "🐻", name: "Ours" },
    { symbol: "🐧", name: "Pingouin" },
    { symbol: "🐦", name: "Oiseau" },
    { symbol: "🦅", name: "Aigle" },
    { symbol: "🦉", name: "Hibou" },
    { symbol: "🦩", name: "Flamant rose" },
    { symbol: "🐠", name: "Poisson" },
    { symbol: "🐟", name: "poisson" },
    { symbol: "🐡", name: "Poisson" },
    { symbol: "🐬", name: "Dauphin" },
    { symbol: "🐋", name: "Baleine" },
    { symbol: "🐍", name: "Serpent" },
    { symbol: "🦎", name: "Lézard" },
    { symbol: "🐊", name: "Crocodile" },
    { symbol: "🐢", name: "Tortue" },
    { symbol: "🐜", name: "Fourmi" },
    { symbol: "🐝", name: "Abeille" },
    { symbol: "🦋", name: "Papillon" },
    { symbol: "🐞", name: "Coccinelle" },
    { symbol: "🦗", name: "Sauterelle" },
    { symbol: "🕷️", name: "Araignée" },
    { symbol: "🕸️", name: "Toile d'araignée" },
    { symbol: "🌳", name: "Arbre" },
    { symbol: "🌲", name: "Sapin" },
    { symbol: "🌴", name: "Palmier" },
    { symbol: "🌵", name: "Cactus" },
    { symbol: "🌾", name: "Herbe" },
    { symbol: "🍀", name: "Trèfle" },
    { symbol: "🌹", name: "Rose" },
    { symbol: "🌻", name: "Tournesol" },
    { symbol: "🌼", name: "Fleur" },
    { symbol: "🌸", name: "Fleur de cerisier" },
    { symbol: "🌺", name: "Hibiscus" },
    { symbol: "🌷", name: "Tulipe" },
    { symbol: "🌿", name: "Feuille" },
  ],
};
